#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_si.py — 从结果 CSV 生成第三篇 Supplementary Materials（md）"""
import pathlib
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent
IT = ROOT.parent / "feat_density_interaction.csv"
DESC = pathlib.Path(r"D:\Codex\MEC-Workspace\data\il_descriptors.csv")
OUT = ROOT / "supplementary_materials.md"
BUCKETS = ["1", "2-3", "4-9", "10-24", "25+"]
PROPS = ["conductivity", "density", "viscosity", "melting_point"]
PLABEL = {
    "conductivity": "Conductivity (ln κ)",
    "density": "Density",
    "viscosity": "Viscosity (ln η)",
    "melting_point": "Melting point (K)",
}


def main():
    it = pd.read_csv(IT)
    lines = [
        "# Supplementary Materials for",
        "",
        "## Full-spectrum descriptors substitute for data density in ionic-liquid property prediction",
        "",
        "Fuxing Lin, Hunan Institute of Engineering",
        "",
        "---",
        "",
        "## S1. Data and descriptor construction",
        "",
        "The model-ready dataset comprises 84,077 experimental records for 1,891 unique ion pairs across four properties "
        "(viscosity, density, electrical conductivity, melting point), compiled and unit-standardized in the companion study "
        "from ILThermo v2.0, ILest, and iolitech (K, mPa·s, g/cm³, S/m; verified SMILES). For every unique ion pair, the complete "
        "RDKit descriptor list was computed independently for the cation and the anion (229 per fragment; 458 total), and "
        "temperature was appended for the three temperature-dependent properties. Descriptor columns undefined for all ions were "
        "removed; remaining missing values were imputed by column median, then zero.",
        "",
        "## S2. Complete stratified interaction table",
        "",
        "All stratified results use 5-fold GroupKFold on IL identity with histogram gradient boosting (200 trees, default "
        "hyperparameters); metrics are computed on pooled out-of-fold predictions within each per-IL record-count bucket. "
        "`base` = ten hand-picked merged descriptors (+ temperature); `full` = 458 per-ion descriptors (+ temperature).",
        "",
        "**Table S1. Group-disjoint R² within per-IL record-count buckets.**",
        "",
        "| Property | Bucket | Set | R² | MAE | Samples | ILs |",
        "|---|---|---|---|---|---|---|",
    ]
    for p in PROPS:
        d = it[it["prop"] == p]
        for b in BUCKETS:
            db = d[d["bucket"] == b]
            if db.empty:
                continue
            for s in ("base", "full"):
                r = db[db["set"] == s]
                if r.empty:
                    continue
                r = r.iloc[0]
                lines.append(
                    f"| {PLABEL[p]} | {b} | {s} | {r['R2']:.4f} | {r['MAE']:.4f} | {int(r['n'])} | {int(r['n_il'])} |"
                )
        lines.append("")

    desc = pd.read_csv(DESC, nrows=1)
    cols = [c for c in desc.columns if c.startswith("cat_") or c.startswith("an_")]
    cats = [c[4:] for c in cols if c.startswith("cat_")]
    ans = [c[3:] for c in cols if c.startswith("an_")]
    lines += [
        "## S3. Descriptor list",
        "",
        f"Each ion pair is represented by {len(cats)} cation descriptors and {len(ans)} anion descriptors "
        f"({len(cats) + len(ans)} total), listed below. Temperature is appended for conductivity, density, and viscosity.",
        "",
        "**Table S2. Cation descriptors.**",
        "",
        "| # | Descriptor |",
        "|---|---|",
    ]
    lines += [f"| {i+1} | {c} |" for i, c in enumerate(cats)]
    lines += [
        "",
        "**Table S3. Anion descriptors.**",
        "",
        "| # | Descriptor |",
        "|---|---|",
    ]
    lines += [f"| {i+1} | {c} |" for i, c in enumerate(ans)]
    lines += [
        "",
        "## S4. Reproducibility",
        "",
        "Environment: Python 3.12, pandas 3.0.5, scikit-learn 1.9.0, RDKit 2026.03.5. Models: "
        "`GradientBoostingRegressor(random_state=0)` for the overall comparison (Table 1 of the main text) and "
        "`HistGradientBoostingRegressor(max_iter=200, learning_rate=0.1, random_state=0)` for the stratified analysis "
        "(Fig. 1 and Table S1); 5-fold `GroupKFold` on IL identity. Viscosity and conductivity targets are log-transformed. "
        "Scripts: `feat_scale_exp.py` (overall comparison) and `feat_density_interaction.py` (stratified interaction); "
        "descriptors generated by `il_descriptors.py`. Data and code are available at GitHub "
        "(linfuxing123/IL-Property-ML, v1.2.0) and archived on Zenodo (concept DOI 10.5281/zenodo.21898948).",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("saved", OUT, "| 行数", len(lines), "| cat", len(cats), "an", len(ans))


if __name__ == "__main__":
    main()
